### ISSUE TITLE
Stuck in an alternate universe.

### ISSUE THREAD

**Issue by Rafin0704** [opencoca/lt2d_school#18]
After hopping onto Jitsi, I seem to be in an alternate matrix where I'm all alone in any class but after I close the tab and reopen the Jitsi app I find myself back in the same room but now filled with other people.

**Comment by opencoca** [comment]
If that happens again, please note the "share address" before and after refreshing the room.

**Comment by opencoca** [comment]
This should now be resolved. See: https://github.com/jitsi/jitsi-meet/issues/5230
