### ISSUE TITLE
Be able to hide people who do not have their camera's on or not sharing their screen so that recording sessions is better.

### ISSUE THREAD

**Issue by Rafin0704** [opencoca/lt2d_school#20]
Like on ZOOM, maybe add a "Hide" button so that you're only able to see the people with their camera on so that it makes it better for recording videos.

**Comment by shadowlerone** [comment]
That'll probably have to be a jitsi thing. Since the meetings are embedded in `<iFrame>` s, we can't modify them directly.
I can look into it further but I'm pretty sure that's not a thing we can do directly in the platform.
I'll look into it further.

**Comment by opencoca** [comment]
Yep, it's a Jitisi thing and implementing it results in complex security implications. There're teams at Webex and IBM looking into how to implement this in all meeting rooms.  For the time being, Jitsi does not have plans to add this to UI.  

Until it's available directly with Jitsi, I think it's best to implement this as both a "Videographer browser extension" and a secure recording room feature.
